---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aiobotocore
  - aiofiles
  - aiohttp
  - annotated-types
  - anyio
  - appdirs
  - arrow
  - async-timeout
  - attrs
  - azure-storage-file-datalake
  - beautifulsoup4
  - black
  - blinker
  - bokeh
  - boto3
  - botocore
  - cachetools
  - calver
  - cffi
  - chardet
  - charset-normalizer
  - click
  - click-plugins
  - cloudpickle
  - colorama
  - databricks-sql-connector
  - distlib
  - django
  - docutils
  - email-validator
  - faker
  - fastavro
  - filelock
  - findpython
  - flatbuffers
  - freezegun
  - fsspec
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-cloud-bigtable
  - google-cloud-logging
  - google-cloud-vision
  - googleapis-common-protos
  - graphviz
  - grpcio-status
  - h11
  - h2
  - hatch-fancy-pypi-readme
  - hatch-vcs
  - hatchling
  - httpcore
  - httpx
  - humanize
  - hyperframe
  - idna
  - importlib-metadata
  - iniconfig
  - isort
  - jinja2
  - json5
  - jupyter-events
  - keras
  - limits
  - loguru
  - markdown
  - markdown-it-py
  - markupsafe
  - marshmallow
  - matplotlib-inline
  - mdurl
  - meson-python
  - microsoft-kiota-http
  - mock
  - more-itertools
  - msal-extensions
  - multidict
  - mypy
  - mypy-extensions
  - ninja
  - numpy
  - oscrypto
  - packaging
  - pandas
  - patchelf
  - pathspec
  - pbr
  - platformdirs
  - pluggy
  - ply
  - prompt-toolkit
  - propcache
  - pyasn1
  - pyasn1-modules
  - pydantic
  - pydantic-core
  - pydantic-settings
  - pygments
  - pyjwt
  - pyproject-api
  - pyproject-metadata
  - pytest
  - python-dateutil
  - pytz
  - pyyaml
  - readme-renderer
  - requests
  - responses
  - rfc3986-validator
  - rich
  - rsa
  - s3fs
  - s3transfer
  - scikit-build-core
  - seaborn
  - sentry-sdk
  - setuptools
  - setuptools-scm
  - six
  - sniffio
  - snowflake-connector-python
  - soupsieve
  - sqlparse
  - tableauserverclient
  - tblib
  - thriftpy2
  - tomlkit
  - toolz
  - tornado
  - tox
  - tqdm
  - trove-classifiers
  - types-psutil
  - types-python-dateutil
  - types-setuptools
  - typing-extensions
  - tzdata
  - urllib3
  - virtualenv
  - wcwidth
  - wheel
  - widgetsnbextension
  - wrapt
  - xyzservices
  - zipp
