---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aiobotocore
  - aiohttp
  - annotated-types
  - anyio
  - appdirs
  - arrow
  - attrs
  - beautifulsoup4
  - black
  - blinker
  - bokeh
  - boto3
  - botocore
  - cachetools
  - calver
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - distlib
  - django
  - docutils
  - faker
  - fastavro
  - filelock
  - flatbuffers
  - freezegun
  - fsspec
  - google-api-core
  - google-auth
  - google-cloud-vision
  - googleapis-common-protos
  - grpcio-status
  - h11
  - h2
  - hatch-fancy-pypi-readme
  - hatch-vcs
  - hatchling
  - httpcore
  - httpx
  - humanize
  - hyperframe
  - idna
  - importlib-metadata
  - iniconfig
  - isort
  - jinja2
  - jupyter-events
  - keras
  - limits
  - loguru
  - markdown
  - markdown-it-py
  - markupsafe
  - marshmallow
  - mdurl
  - meson-python
  - microsoft-kiota-http
  - mock
  - more-itertools
  - mypy
  - mypy-extensions
  - ninja
  - numpy
  - oscrypto
  - packaging
  - pandas
  - patchelf
  - pathspec
  - platformdirs
  - pluggy
  - prompt-toolkit
  - pyasn1
  - pyasn1-modules
  - pydantic
  - pydantic-core
  - pygments
  - pyjwt
  - pyproject-api
  - pyproject-metadata
  - pytest
  - python-dateutil
  - pytz
  - pyyaml
  - readme-renderer
  - requests
  - rfc3986-validator
  - rich
  - rsa
  - s3fs
  - s3transfer
  - scikit-build-core
  - seaborn
  - setuptools
  - setuptools-scm
  - sniffio
  - soupsieve
  - sqlparse
  - tomlkit
  - tox
  - tqdm
  - trove-classifiers
  - types-psutil
  - types-python-dateutil
  - types-setuptools
  - typing-extensions
  - tzdata
  - urllib3
  - virtualenv
  - wcwidth
  - wheel
  - widgetsnbextension
  - wrapt
  - xyzservices
  - zipp
