---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - absl-py
  - adal
  - aiobotocore
  - aiofiles
  - aiohappyeyeballs
  - aiohttp
  - aioitertools
  - alembic
  - annotated-types
  - anyio
  - appdirs
  - argcomplete
  - argon2-cffi
  - arrow
  - asgiref
  - asn1crypto
  - astroid
  - asttokens
  - async-lru
  - async-timeout
  - attrs
  - authlib
  - aws-lambda-powertools
  - awscli
  - awswrangler
  - azure-core
  - azure-identity
  - azure-keyvault-secrets
  - azure-storage-blob
  - azure-storage-file-datalake
  - babel
  - backoff
  - backports-tarfile
  - beautifulsoup4
  - black
  - bleach
  - blinker
  - bokeh
  - boto3
  - botocore
  - build
  - cachecontrol
  - cachetools
  - calver
  - cattrs
  - cffi
  - cfgv
  - chardet
  - charset-normalizer
  - cleo
  - click
  - click-plugins
  - cloudpickle
  - colorama
  - colorlog
  - comm
  - coverage
  - crashtest
  - croniter
  - cycler
  - cython
  - databricks-sdk
  - databricks-sql-connector
  - dataclasses-json
  - datadog
  - debugpy
  - decorator
  - deepdiff
  - defusedxml
  - deprecated
  - distlib
  - distro
  - django
  - dnspython
  - docker
  - docstring-parser
  - docutils
  - dulwich
  - durationpy
  - editables
  - elasticsearch
  - email-validator
  - et-xmlfile
  - eventlet
  - exceptiongroup
  - execnet
  - executing
  - faker
  - fastapi
  - fastavro
  - fastjsonschema
  - filelock
  - findpython
  - flake8
  - flatbuffers
  - fonttools
  - fqdn
  - freezegun
  - frozenlist
  - fsspec
  - future
  - gcloud-aio-auth
  - gcloud-aio-bigquery
  - gcsfs
  - gevent
  - gitdb
  - gitpython
  - google-ads
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - google-cloud-aiplatform
  - google-cloud-audit-log
  - google-cloud-bigquery
  - google-cloud-bigquery-storage
  - google-cloud-bigtable
  - google-cloud-dataproc
  - google-cloud-logging
  - google-cloud-pubsub
  - google-cloud-resource-manager
  - google-cloud-secret-manager
  - google-cloud-storage
  - google-cloud-vision
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - graphql-core
  - graphviz
  - greenlet
  - grpc-google-iam-v1
  - grpcio
  - grpcio-health-checking
  - grpcio-status
  - grpcio-tools
  - gunicorn
  - h11
  - h2
  - hatch-fancy-pypi-readme
  - hatch-vcs
  - hatchling
  - hpack
  - httpcore
  - httplib2
  - httptools
  - httpx
  - humanfriendly
  - humanize
  - hvac
  - hyperframe
  - identify
  - idna
  - imageio
  - importlib-metadata
  - importlib-resources
  - inflection
  - iniconfig
  - installer
  - ipython
  - isodate
  - isoduration
  - isort
  - itsdangerous
  - jaraco-context
  - jaraco-functools
  - jedi
  - jeepney
  - jinja2
  - jmespath
  - joblib
  - json5
  - jsonpatch
  - jsonpointer
  - jupyter-client
  - jupyter-core
  - keras
  - keyring
  - kiwisolver
  - langchain
  - langchain-core
  - langsmith
  - lazy-object-proxy
  - limits
  - loguru
  - lxml
  - lz4
  - mako
  - markdown
  - markdown-it-py
  - markupsafe
  - marshmallow
  - matplotlib-inline
  - mccabe
  - mdurl
  - meson-python
  - microsoft-kiota-http
  - mistune
  - mock
  - more-itertools
  - mpmath
  - msal
  - msal-extensions
  - msgpack
  - multidict
  - multiprocess
  - mypy
  - mypy-extensions
  - narwhals
  - nest-asyncio
  - networkx
  - ninja
  - nltk
  - nodeenv
  - numpy
  - oauth2client
  - oauthlib
  - openpyxl
  - opentelemetry-exporter-otlp
  - opentelemetry-exporter-prometheus
  - opentelemetry-instrumentation
  - opentelemetry-instrumentation-requests
  - opentelemetry-proto
  - opentelemetry-sdk
  - opentelemetry-semantic-conventions
  - opentelemetry-util-http
  - oscrypto
  - overrides
  - packaging
  - pandas
  - pandas-gbq
  - pandocfilters
  - paramiko
  - parso
  - patchelf
  - pathspec
  - pbr
  - pexpect
  - pg8000
  - pillow
  - pinotdb
  - pip
  - pkginfo
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - ply
  - poetry-core
  - poetry-plugin-export
  - portalocker
  - pre-commit
  - prometheus-client
  - prompt-toolkit
  - propcache
  - proto-plus
  - protobuf
  - psutil
  - ptyprocess
  - pure-eval
  - py
  - py4j
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pycryptodomex
  - pydantic
  - pydantic-settings
  - pyflakes
  - pygithub
  - pygments
  - pyjwt
  - pylint
  - pymongo
  - pymysql
  - pyopenssl
  - pyparsing
  - pyproject-api
  - pyproject-hooks
  - pyproject-metadata
  - pyrsistent
  - pyspark
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - python-dateutil
  - python-dotenv
  - python-json-logger
  - python-multipart
  - python-slugify
  - python-telegram-bot
  - pytz
  - pyyaml
  - readme-renderer
  - redis
  - regex
  - requests
  - requests-aws4auth
  - requests-file
  - responses
  - retry
  - rfc3339-validator
  - rfc3986
  - rfc3986-validator
  - rich
  - rich-toolkit
  - rsa
  - s3fs
  - s3transfer
  - schema
  - scikit-build-core
  - scramp
  - seaborn
  - semver
  - sentry-sdk
  - setproctitle
  - setuptools
  - setuptools-scm
  - shellingham
  - simplejson
  - six
  - slack-sdk
  - smart-open
  - smmap
  - sniffio
  - snowflake-connector-python
  - sortedcontainers
  - soupsieve
  - sphinx
  - sqlalchemy
  - sqlalchemy-bigquery
  - sqlalchemy-spanner
  - sqlparse
  - sshtunnel
  - stack-data
  - starlette
  - sympy
  - tableauserverclient
  - tabulate
  - tblib
  - tenacity
  - termcolor
  - terminado
  - threadpoolctl
  - thrift
  - thriftpy2
  - tinycss2
  - toml
  - tomlkit
  - toolz
  - tornado
  - tox
  - tqdm
  - traitlets
  - trove-classifiers
  - typeguard
  - typer
  - types-protobuf
  - types-psutil
  - types-python-dateutil
  - types-pytz
  - types-pyyaml
  - types-requests
  - types-setuptools
  - typing-extensions
  - typing-inspect
  - typing-inspection
  - tzdata
  - tzlocal
  - urllib3
  - uvicorn
  - uvloop
  - virtualenv
  - watchdog
  - wcwidth
  - weaviate-client
  - webcolors
  - webencodings
  - websocket-client
  - websockets
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - wsproto
  - xlsxwriter
  - xmltodict
  - xyzservices
  - yamllint
  - yandexcloud
  - yarl
  - zipp
  - zstandard
